# Generated by Django 2.0.5 on 2018-05-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', models.TextField(blank=True, db_column='Urlid', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('page', models.TextField(blank=True, db_column='Page', null=True)),
                ('rank', models.TextField(blank=True, db_column='Rank', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('client', models.TextField(blank=True, db_column='Client', null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
    ]
