# Generated by Django 2.0.5 on 2018-05-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': True},
        ),
    ]
