# Generated by Django 2.0.5 on 2018-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0002_keyword2'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyword3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picsrc', models.TextField(blank=True, null=True)),
                ('urlid', models.CharField(blank=True, max_length=20, null=True)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('page', models.CharField(blank=True, max_length=5, null=True)),
                ('rank', models.CharField(blank=True, max_length=5, null=True)),
                ('client', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('updatatime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
