# Generated by Django 2.0.5 on 2018-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0005_auto_20180505_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='client',
            field=models.TextField(blank=True, db_column='Client', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.TextField(blank=True, db_column='Keyword', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='page',
            field=models.TextField(blank=True, db_column='Page', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='rank',
            field=models.TextField(blank=True, db_column='Rank', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='urlid',
            field=models.TextField(blank=True, db_column='Urlid', null=True),
        ),
    ]
