# Generated by Django 2.0.5 on 2018-05-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0006_auto_20180505_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='time',
        ),
    ]
