# Generated by Django 2.0.5 on 2018-05-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0009_auto_20180505_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': True},
        ),
    ]
