# Generated by Django 2.0.5 on 2018-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0013_auto_20180505_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time',
            field=models.DateTimeField(auto_now=True, db_column='Time', null=True),
        ),
    ]
