# Generated by Django 2.0.5 on 2018-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0014_auto_20180505_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': False},
        ),
    ]
