# Generated by Django 2.0.5 on 2018-05-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0015_auto_20180505_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': True},
        ),
    ]
