# Generated by Django 2.0.5 on 2018-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0016_auto_20180505_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='time',
            field=models.DateTimeField(blank=True, db_column='Time', null=True),
        ),
    ]
