# Generated by Django 2.0.5 on 2018-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0017_auto_20180505_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
