# Generated by Django 2.0.5 on 2018-05-05 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0019_auto_20180505_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
