# Generated by Django 2.0.5 on 2018-05-05 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0021_auto_20180505_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateField(default=datetime.date(2018, 5, 5), null=True),
        ),
    ]
