# Generated by Django 2.0.5 on 2018-05-05 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0022_auto_20180505_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 11, 30, 5, 498770), null=True),
        ),
    ]
