# Generated by Django 2.0.5 on 2018-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0023_auto_20180505_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
