# Generated by Django 2.0.5 on 2018-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0025_auto_20180505_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
