# Generated by Django 2.0.5 on 2018-05-05 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0026_auto_20180505_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='img',
            field=models.CharField(blank=True, db_column='Img', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 17, 54, 46, 381530), null=True),
        ),
    ]
