# Generated by Django 2.0.5 on 2018-05-05 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0027_auto_20180505_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='img',
            field=models.URLField(blank=True, db_column='Img', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 17, 58, 8, 639442), null=True),
        ),
    ]
