# Generated by Django 2.0.5 on 2018-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0028_auto_20180505_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='time2',
        ),
        migrations.AddField(
            model_name='keyword',
            name='time',
            field=models.TextField(blank=True, db_column='Time', null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='img',
            field=models.TextField(blank=True, db_column='Img', null=True),
        ),
    ]
