# Generated by Django 2.0.5 on 2018-05-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0029_auto_20180505_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': False},
        ),
    ]
