# Generated by Django 2.0.5 on 2018-05-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0030_auto_20180505_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': True},
        ),
    ]
