# Generated by Django 2.0.5 on 2018-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0031_auto_20180505_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='img',
            field=models.URLField(blank=True, db_column='Img', null=True),
        ),
    ]
