# Generated by Django 2.0.5 on 2018-05-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0032_auto_20180505_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': False},
        ),
    ]
