# Generated by Django 2.0.5 on 2018-05-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0033_auto_20180505_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': True},
        ),
    ]
