# Generated by Django 2.0.5 on 2018-05-05 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0034_auto_20180505_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='img',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='time',
        ),
        migrations.AddField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 5, 21, 30, 5, 766730), null=True),
        ),
    ]
