# Generated by Django 2.0.5 on 2018-05-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0035_auto_20180505_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'managed': False},
        ),
    ]
