# Generated by Django 2.0.5 on 2018-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0038_auto_20180505_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='img',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='time',
        ),
        migrations.AddField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
