# Generated by Django 2.0.5 on 2018-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0042_auto_20180506_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
