# Generated by Django 2.0.5 on 2018-05-06 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0043_auto_20180506_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 6, 8, 10, 13, 362976), null=True),
        ),
    ]
