# Generated by Django 2.0.5 on 2018-05-06 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquire', '0044_auto_20180506_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='time2',
            field=models.DateField(blank=True, default=datetime.date(2018, 5, 6), null=True),
        ),
    ]
